### ISSUE TITLE
config.json content erased and no message saved

### ISSUE THREAD

**Issue by hammenm** [mattermost/mattermost-plugin-welcomebot#116]
Hello,

I installed the plugin on our own deployed instance. Then I created a message for the team "zeilt-studio" in the `config.json` file.
However, when I try to display the list of existing messages, the bot prints "There are no welcome messages defined".
Moreover, when I update my config.json file, the content I added disappear.
We are on version 7.8.5
Here is the exact content that I added:

```json
"com.mattermost.welcomebot": {
    "WelcomeMessages": [
        {
            "TeamName": "zeilt-studio",
            "DelayInSeconds": 5,
            "Message": [
                "### Welcome {{.UserDisplayName}} to the Staff {{.Team.DisplayName}} team!",
                "",
                "If you have any questions about your account, please message your @system-admin.",
                "",
                "For feedback about the Mattermost app, please share in the ~mattermost channel."
            ]
        }
    ]
},
```

Is it a know behavior. Did I forget something ?

Thank you very much!

**Comment by mickmister** [comment]
Hi @hammenm, if you edit the server's `config.json` file manualy, you also need to restart the server for the changes to take effect. Did you happen to try this?

> Moreover, when I update my config.json file, the content I added disappear.

It's possible a different config save happened through the UI before the server was restarted. Do you think this might be the case?

**Comment by Kshitij-Katiyar** [comment]
@mickmister Should we close this issue if the question has been answered ?
