### ISSUE TITLE
Failed to create welcomebot user

### ISSUE THREAD

**Issue by SurferLancelot** [mattermost/mattermost-plugin-welcomebot#17]
Hi Guys 

Noticed an issue here where the welcomebot cannot create the welcombot user if the option for accepted domains is set.

{"level":"error","ts":1561111697.1033537,"caller":"mlog/sugar.go:23","msg":"CreateUser: The email you provided does not belong to an accepted domain. Please contact your administrator or sign up with a different email., ","plugin_id":"com.mattermost.welcomebot"}

Welcome bot user is created with the email: welcomebot@mattermost.com

Workaround is to delete the accepted domains from the list or add mattermost.com to the accepted domain list both of these affect the level of security of the instance.

Regards
Lancealot

**Comment by levb** [comment]
Related to https://mattermost.atlassian.net/browse/MM-19042?

**Comment by cpoile** [comment]
@levb Nope, not related. I can still look at this if you want?

**Comment by levb** [comment]
Probably easiest to make the email address for the bot configurable. cc @aaronrothschild

**Comment by hanzei** [comment]
@SurferLancelot What server version are you using? I suppose this bug was fixed with https://github.com/mattermost/mattermost-server/pull/12041 in 5.15

**Comment by aaronrothschild** [comment]
@levb Agreed, the right way is to make the bot email address configurable. But I'm not sure where any user would ever see it.  

It also seems like this particular issue was solved as @hanzei mentioned.  I'm not planning to open a ticket to set the email for the bot which no user will ever see.  Let me know if there is a place this would become visible (aside from an admin who can see the user's account email).

**Comment by hanzei** [comment]
Dosing as this is fixed with https://github.com/mattermost/mattermost-server/pull/12041
