### ISSUE TITLE
Welcome bot message is not triggering on new user 

### ISSUE THREAD

**Issue by kumarrahul-rkv** [mattermost/mattermost-plugin-welcomebot#22]
I have added configuration in `config.json` file as follows:

`
"Plugins": {
            "com.mattermost.welcomebot": {
                "welcomemessages": [
                    {
                        "DelayInSeconds": 2,
                        "Message": [
                            "### Welcome {{.UserDisplayName}} to the {{.Team.DisplayName}} team!",
                            "",
                            "If you have any questions about your account, please message your @ibartsindia."
                        ],
                        "TeamName": "workplace"
                    },
                    {
                        "Actions": [
                            {
                                "ActionDisplayName": "Director",
                                "ActionName": "director-action",
                                "ActionSuccessfulMessage": [
                                    "### Awesome! I have added you to the following developer channels:",
                                    "~core-team - This channel is for core team day to day planning.",
                                    "~web-development - To discuss topics related to Web Development",
                                    "~app-development - To discuss topics related to App Development",
                                    "~hr-work- To discuss HR related topics",
                                    "~management-team- To discuss topics related to management"
                                ],
                                "ActionType": "button",
                                "ChannelsAddedTo": [
                                    "core-team",
                                    "web-development",
                                    "app-development",
                                    "hr-work",
                                    "management-team"
                                ]
                            },
                            {
                                "ActionDisplayName": "Supervisor",
                                "ActionName": "supervisor-action",
                                "ActionSuccessfulMessage": [
                                    "### Awesome! I have added you to the following developer channels:",
                                    "~core-team - This channel is for core team day to day planning.",
                                    "~web-development - To discuss topics related to Web Development",
                                    "~app-development - To discuss topics related to App Development",
                                    "~hr-work- To discuss HR related topics",
                                    "~management-team- To discuss topics related to management"
                                ],
                                "ActionType": "button",
                                "ChannelsAddedTo": [
                                    "core-team",
                                    "web-development",
                                    "app-development",
                                    "hr-work",
                                    "management-team"
                                ]
                            },
                            {
                                "ActionDisplayName": "HR",
                                "ActionName": "hr-action",
                                "ActionSuccessfulMessage": [
                                    "### Awesome! I have added you to the following developer channels:",
                                    "~hr-work- To discuss HR related topics"
                                ],
                                "ActionType": "button",
                                "ChannelsAddedTo": [
                                    "hr-work"
                                ]
                            },
                            {
                                "ActionDisplayName": "Senior Manager",
                                "ActionName": "senior-manager-action",
                                "ActionSuccessfulMessage": [
                                    "### Awesome! I have added you to the following developer channels:",
                                    "~core-team - This channel is for core team day to day planning.",
                                    "~web-development - To discuss topics related to Web Development",
                                    "~app-development - To discuss topics related to App Development",
                                    "~hr-work- To discuss HR related topics",
                                    "~management-team- To discuss topics related to management"
                                ],
                                "ActionType": "button",
                                "ChannelsAddedTo": [
                                    "core-team",
                                    "web-development",
                                    "app-development",
                                    "hr-work",
                                    "management-team"
                                ]
                            },
                            {
                                "ActionDisplayName": "Assistant Manager",
                                "ActionName": "assistant-manager-action",
                                "ActionSuccessfulMessage": [
                                    "### Awesome! I have added you to the following developer channels:",
                                    "~web-development - To discuss topics related to Web Development",
                                    "~app-development - To discuss topics related to App Development",
                                    "~management-team- To discuss topics related to management"
                                ],
                                "ActionType": "button",
                                "ChannelsAddedTo": [
                                    "management-team",
                                    "web-development",
                                    "app-development"
                                ]
                            },
                            {
                                "ActionDisplayName": "Web Developer",
                                "ActionName": "web-developer-action",
                                "ActionSuccessfulMessage": [
                                    "### Awesome! I have added you to the following developer channels:",
                                    "~web-development - To discuss topics related to Web Development"
                                ],
                                "ActionType": "button",
                                "ChannelsAddedTo": [
                                    "web-development"
                                ]
                            },
                            {
                                "ActionDisplayName": "App Developer",
                                "ActionName": "support-action",
                                "ActionSuccessfulMessage": [
                                    "### Awesome! I have added you to the following developer channels:",
                                    "~app-development - To discuss topics related to App Development"
                                ],
                                "ActionType": "button",
                                "ChannelsAddedTo": [
                                    "app-development"
                                ]
                            },
                            {
                                "ActionDisplayName": "SEO Executive",
                                "ActionName": "seo-executive-action",
                                "ActionSuccessfulMessage": [
                                    "### Awesome! I have added you to the following developer channels:",
                                    "~web-development - To discuss topics related to Web Development",
                                    "~seo-work - To discuss topics related to SEO Work"
                                ],
                                "ActionType": "button",
                                "ChannelsAddedTo": [
                                    "seo-work",
                                    "web-development"
                                ]
                            }
                        ],
                        "AttachmentMessage": [
                            "Let's get started by adding you to key channels! What is your role in the company?"
                        ],
                        "DelayInSeconds": 5,
                        "TeamName": "workplace"
                    }
                ]
            }
        },
        "PluginStates": {
            "com.mattermost.welcomebot": {
                "Enable": true
            }
        }
`

Here is my team name:

![image](https://user-images.githubusercontent.com/19572222/65743592-f35b0400-e112-11e9-9f06-4de7c16daa0a.png)

**Comment by kumarrahul-rkv** [comment]
Resolved

**Comment by umlaeute** [comment]
@kumarrahul-rkv how did you resolve this?

(because right now i have a similar problem: welcomebot is installed and configured; `/welcomebot preview mychannel` works; but new users don't see anything)
