### ISSUE TITLE
When a user joins a channel, present them with a Welcome message

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-welcomebot#24]
When a user joins a channel, it would be great if the channel admin could set a "Welcome Message" for new members to the channel.  

it woud be cool if there was a `/welcome set_channel_welcome "Hi Welcome to this channel, be nice"`

The settings could also live in the channel menu bar when we add that to the plugin API.

**Comment by jozuenoon** [comment]
I'm digging into that :)

**Comment by hanzei** [comment]
Thanks @jozuenoon :+1:

**Comment by levb** [comment]
@jozuenoon Are you still interested in finishing this ticket, or should we put it back in the "Up for grabs" bucket?

**Comment by jozuenoon** [comment]
@levb I will follow up soon if it's not so urgent.

**Comment by levb** [comment]
@jozuenoon Are you still interested in finishing the ticket?

**Comment by vespian** [comment]
I can have a look at it. Once https://github.com/mattermost/mattermost-plugin-welcomebot/pull/29 lands, implementing extra command should not be hard.

**Comment by levb** [comment]
@vespian go for it

**Comment by vespian** [comment]
@aaronrothschild I would like to make sure - according to [1] `channel admin` is an enterprise feature so this would limit the users of the `channel welcome` setting of /welcomebot to EE users only. Right? 
Do you mind if we allow sysadmins as well?

[1] https://docs.mattermost.com/help/getting-started/managing-members.html#channel-admin

**Comment by vespian** [comment]
@levb Short update - did not manage to pick it up this weekend, will look into it next week/I still have it on my radar.

**Comment by vespian** [comment]
Please have a look at https://github.com/mattermost/mattermost-plugin-welcomebot/pull/31
