### ISSUE TITLE
Testing new messages

### ISSUE THREAD

**Issue by kelsiuss** [mattermost/mattermost-plugin-welcomebot#26]
We would like to see what our welcome message looks like, but have no way to test this before launching it on the server.

**Comment by levb** [comment]
@aaronrothschild Can we do this as a (sysadmin) command that would DM the message to the admin?

**Comment by vespian** [comment]
I would like to give it a try.

**Comment by vespian** [comment]
Please have a look at https://github.com/mattermost/mattermost-plugin-welcomebot/pull/29
