### ISSUE TITLE
Unable to send ephemeral message from inside of the hook

### ISSUE THREAD

**Issue by vespian** [mattermost/mattermost-plugin-welcomebot#32]
This is a followup of the discussion in https://github.com/mattermost/mattermost-plugin-welcomebot/pull/31#issuecomment-598902949 and https://github.com/mattermost/mattermost-plugin-welcomebot/pull/31#issuecomment-597223708.

For some reason, from within `UserHasJoinedChannel` hook it is impossible to send an ephemeral message using `p.API.SendEphemeralPost()`. It is unclear/has not been tested if this is limited to this hook only.

The problem needs to be investigated and the underlying issue fixed.

**Comment by hanzei** [comment]
See https://github.com/mattermost/mattermost-plugin-welcomebot/pull/31#discussion_r396102799 for the reason why is his happening

**Comment by jfrerich** [comment]
This issue will be resolved after merging https://github.com/mattermost/mattermost-plugin-welcomebot/pull/31.

**Comment by hanzei** [comment]
Fixed with #31
