### ISSUE TITLE
Make channel welcome messages use ephemeral messages.

### ISSUE THREAD

**Issue by vespian** [mattermost/mattermost-plugin-welcomebot#33]
This is a followup of the discussion in https://github.com/mattermost/mattermost-plugin-welcomebot/pull/31#issuecomment-599735342

Once https://github.com/mattermost/mattermost-plugin-welcomebot/issues/32 gets addressed, the code for the channel welcome messages should be adjusted to use ephemeral posts instead of the plain ones.

**Comment by hanzei** [comment]
Let's resolve the conversation in https://github.com/mattermost/mattermost-plugin-welcomebot/pull/31#discussion_r396102799 first.

**Comment by jfrerich** [comment]
Also resolved by merging latest commit in https://github.com/mattermost/mattermost-plugin-welcomebot/pull/31

**Comment by hanzei** [comment]
Fixed with  #31
