### ISSUE TITLE
Can't seem to get commands to work

### ISSUE THREAD

**Issue by rovsing** [mattermost/mattermost-plugin-welcomebot#39]
I've tried for quite some time, and since nobody elase seems to be having this problem, I'm writing here.

I've got a Mattmost 5.19.1 installed, with Welcomebot 1.1.1 enabled.

However, I cannot get `/welcomebot help/list/preview` to work. When using it, I get the:

`Command with a trigger of '/welcomebot' not found`

Is there anything setup I've missed?

**Comment by mueller-thomas-vse** [comment]
Same here
Mattermost-Version: 5.21.0
latest Version of Bot

**Comment by MarcSN311** [comment]
same here, also on 5.21.0

**Comment by levb** [comment]
I think we made a mistake and merged documentation changes intended for the upcoming 1.2 release into `master`. @jfrerich unless we are 1-2 days away from cutting the release, let's maybe roll-back the doc changes until we have the release ready-to-go?

**Comment by onno-ole** [comment]
Is there a workaround for the time being @levb ?
Tried using 1.1.0 instead but it still isn't working.

**Comment by loganbest** [comment]
Having this same issue on 5.22 of MM. Is there a separate slash command to use?

**Comment by rovsing** [comment]
Are there any updates on this @levb @jfrerich?

**Comment by jfrerich** [comment]
Hi All, we have a release coming up soon that will add the functionality that is currently in the help response.  

After [this PR](https://github.com/mattermost/mattermost-plugin-welcomebot/pull/47) is merged, we'll complete the [v1.2.0 version bump](https://github.com/mattermost/mattermost-plugin-welcomebot/pull/34) and make the release that includes discussed commands

**Comment by MarcSN311** [comment]
It's working for me now.

**Comment by jfrerich** [comment]
With version v1.2.0, the commands in this ticket will now work. Please upgrade to `v1.2.0` and let me know if the issue persists!
