### ISSUE TITLE
Internal Server Error when using /welcomebot

### ISSUE THREAD

**Issue by taylorjason** [mattermost/mattermost-plugin-welcomebot#46]
We have enabled Welcomebot but whenever we run the `/welcomebot` commands we get an "internal server error" message. The welcomebot does work when a member joins a team but none of the slash commands for welcomebot work.

We are using the HA E20 version of MM.

**Comment by hanzei** [comment]
@taylorjason Does the server logs contain any error message related to welcomebot?

**Comment by amyblais** [comment]
There are errors here that may be helpful: https://forum.mattermost.org/t/i-enabled-welcomebot-but-slash-command-welcomebot-is-not-recognized/10019/2
