### ISSUE TITLE
Backend settings

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mattermost-plugin-welcomebot#5]
Any ETA for bot config in MM console?

**Comment by hanzei** [comment]
Hey @uhlhosting,

Are you referring to bot accounts for Mattermost?

**Comment by uhlhosting** [comment]
For the welcome bot settings need to be done via config.json and thats quite not so at hand always. Best would be to manage settings in Console backend.

**Comment by hanzei** [comment]
This needs changes on the Mattermost server. See https://mattermost.atlassian.net/browse/MM-11828 for more context.

**Comment by franckadil** [comment]
@hanzei Hi guys, I tried to add the sample message but Mattermost keeps failing. I tried to put the script in settings as explained but it seems that I am just doing it wrong. 

Can any of please share their confi.json with me or a full screenshot please ?

Thank you in advance for your help!

Cheers,

**Comment by hanzei** [comment]
Hey @franckadil,

Did you modify your `config.json` according to https://github.com/mattermost/mattermost-plugin-welcomebot#usage? If not, would you mind opening a new issue, given that your questions is more like a new  support request?

**Comment by franckadil** [comment]
Hi @hanzei thank you for your prompt reply. I have reached  out yesterday to the community channel in Mattermost, and it appears that the example on the documentation had some errors in it. I implemented the corrections and now it perfectly works! I've seen also that a commit have been done on the Readme.md so that's good  now.

**Comment by hanzei** [comment]
Duplicates  https://github.com/mattermost/mattermost-plugin-welcomebot/issues/42

**Comment by hanzei** [comment]
Duplicate of #42
