### ISSUE TITLE
Add slash command autocomplete functionality

### ISSUE THREAD

**Issue by iomodo** [mattermost/mattermost-plugin-welcomebot#50]
From 5.24 MM server has a slash command autocomplete functionality feature. An API can be found [here](https://github.com/mattermost/mattermost-server/blob/master/model/command_autocomplete.go#L28)
To implement the feature add `AutocompleteData` struct to the `Command` when registering a slash command.

Similar PRs:
For Todo plugin https://github.com/mattermost/mattermost-plugin-todo/pull/69
For Agenda plugin https://github.com/mattermost/mattermost-plugin-agenda/pull/40

**Comment by rahulchheda** [comment]
Would like to take this up @iomodo, seems like a fairly easy issue, can I get more context for this?

**Comment by iomodo** [comment]
Hey @rahulchheda sure, the way to implement this one is to go through the `ExecuteCommand` method in the plugin and convert all commands/subcommands to the autocomplete. You can see in the similar PRs how exactly it is done. If you have any question do not hesitate to ping me on community.

**Comment by iomodo** [comment]
Hey @rahulchheda, are you still working on this? Do you have any questions?

**Comment by rahulchheda** [comment]
Hey @iomodo , will attempt it over this weekend. Sorry for the delay.

**Comment by jfrerich** [comment]
Hi @rahulchheda! Do you have any updates on this issue?  Do you have a PR you could publish as a draft and we could give you some early feedback?
