### ISSUE TITLE
Welcomebot preview not working (team not found)

### ISSUE THREAD

**Issue by acidicX** [mattermost/mattermost-plugin-welcomebot#54]
Hi there,

not sure this is an issue with Mattermost itself or the welcomebot, but the preview command (`/welcomebot preview ABC`) won't find the team name:

```
{"level":"error","ts":1592559079.462729,"caller":"mlog/sugar.go:23","msg":"failed to query team","plugin_id":"com.mattermost.welcomebot","team_name":"ABC","err":"SqlTeamStore.GetByName: Unable to find the existing team., name=ABC,sql: no rows in result set"}
```

I triple-checked the team name in the team settings and even set it to something else and back again to make sure it is correct. Still does not work. Any ideas?

Mattermost Version: 5.24.0
Database Schema Version: 5.24.0
Database: postgres

Welcomebot 1.2.0

**Comment by hanzei** [comment]
Does `/welcomebot preview abc` result in the same error?

**Comment by acidicX** [comment]
@hanzei no, this will give: `team abc has not been found`
Is the sql search always lowercase? I'll try to set the team name to lowercase in the config.json and try that.

**Comment by acidicX** [comment]
Yes that works. I missed that in the docs or it wasn't there when I set it up a few months ago.
