### ISSUE TITLE
Allow restricting welcomebot invitations to non-guest accounts

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-welcomebot#63]
Hey team, is this a known behaviour: on a customer instance it seems the welcomebot is inviting guest accounts to channels and the guests can just join without be added manually?

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/qhxbdgnqg3ykfdyoamkk6wgsqe) *by @flexo3001*._

**Comment by maisnamrajusingh** [comment]
@jfrerich is this something I can help with ?

**Comment by maisnamrajusingh** [comment]
@jfrerich I tried to replicate the issue but couldn't replicate it. Would it be possible to get access to the `config.json` settings the user used for the welcomebot settings ?

**Comment by jfrerich** [comment]
*@jfrerich attached a* [message](https://community.mattermost.com/_redirect/pl/t3uboyzqhpfmzcwbxshhufgj8r) *from @aaronrothschild*

Hmmm...that's an interesting situation.  @dylan.haussermann do we test for this at all?  

This seems like a good new issue: restrict welcomebot messages to "full" users and ignore "guest" users (add an option in config to observe this behavior optionally)

**Comment by jfrerich** [comment]
*@jfrerich attached a* [message](https://community.mattermost.com/_redirect/pl/7956faxbd7n3pb5pnmtah53x5y) *from @aaronrothschild*

@jason.frerich or @shota.gvinepadze I suspect the plugin bot has permissions to add the user to any channel (and does so) - without taking into account they are a guest account.

**Comment by jfrerich** [comment]
*@jfrerich attached a* [message](https://community.mattermost.com/_redirect/pl/7ucz1uc1cbnudrkd6ymg4uthbe) *from @aaronrothschild*

I agree there should be a configuration to disable/enable ignoring a guest user.  For now, let's address the main issue of in a private MM instance, guests should not be invited to welcomebot rules.  If it's an open instance, then users can receive welcomebot messages and get added to room. . 

I could see this gettingmore complex (ie: For guests, show them THIS rule instead, etc.)....but let's start simple.

**Comment by jfrerich** [comment]
> @jfrerich I tried to replicate the issue but couldn't replicate it. Would it be possible to get access to the `config.json` settings the user used for the welcomebot settings ?

@maisnamraju, are you having issues replicating the case where a guest account is getting invited via the welcomebot rules? I believe the ask for this particular ticket is to add the restriction that guest user accounts to not get invited.  @aaronrothschild, is that correct?

**Comment by maisnamraju** [comment]
> > @jfrerich I tried to replicate the issue but couldn't replicate it. Would it be possible to get access to the `config.json` settings the user used for the welcomebot settings ?
> 
> @maisnamraju, are you having issues replicating the case where a guest account is getting invited via the welcomebot rules? I believe the ask for this particular ticket is to add the restriction that guest user accounts to not get invited. @aaronrothschild, is that correct?

Yes, I wanted to replicate this bug. Can you lay out the steps I can use to replicate this issue ?
