### ISSUE TITLE
Configuring Welcome Bot on Mattermost Cloud

### ISSUE THREAD

**Issue by ahmaddanialmohd** [mattermost/mattermost-plugin-welcomebot#64]
Hi, team.

While the Welcome Bot is configurable on `config.json` for the self hosted Mattermost Server, how do we go about configuring this on the Mattermost Cloud solution?

![image](https://user-images.githubusercontent.com/49461314/102100446-65c51a80-3e64-11eb-93e2-f295591a7f46.png)

Any plans on supporting the configuration on the UI level in the future to cater for the Mattermost Cloud system administrator to set up accordingly?

**Comment by hanzei** [comment]
Hi @ahmaddanialmohd,

Welcome bot doesn't properly work on Cloud. It should also not show up in the Marketplace for Cloud instances, but due to a bug it does.

I don't know of any plans of making this plugin work on Cloud. cc @aaronrothschild
