### ISSUE TITLE
getting the error while running the *make* Command for welcome-bot

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-welcomebot#88]
for the mattermost version 5.37 & 6.0, when i Run **make** Command then i'm getting below error 

```bash
qa2@qa-latitude-7480-k:~/github/mattermost/mattermost-plugin-welcomebot$ make
Running golangci-lint
golangci-lint run ./...
WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
build/deploy/main.go:116:8: undeclared name: `archiver` (typecheck)
	err = archiver.Unarchive(bundlePath, targetPath)
	      ^
build/deploy/main.go:12:2: "github.com/mholt/archiver/v3" imported but not used (typecheck)
	"github.com/mholt/archiver/v3"
	^
server/command.go:45:8: p.API undefined (type *Plugin has no field or method API) (typecheck)
	_ = p.API.SendEphemeralPost(args.UserId, post)
	      ^
server/command.go:49:20: p.API undefined (type *Plugin has no field or method API) (typecheck)
	user, appErr := p.API.GetUser(userID)
	                  ^
server/command.go:131:27: p.API undefined (type *Plugin has no field or method API) (typecheck)
	channelInfo, appErr := p.API.GetChannel(args.ChannelId)
	                         ^
../../../../../snap/golangci-lint/36/src/runtime/cgo/cgo.go:34:8: could not import C (cgo preprocessing failed) (typecheck)
import "C"
       ^
make: *** [Makefile:47: golangci-lint] Error 1
```

My go version is *go version go1.17.2 linux/amd64*
NPM version **7.7.6**
node version **v15.14.0**

![Screenshot from 2021-11-23 00-10-34](https://user-images.githubusercontent.com/89907719/142918138-aba852db-9213-4ffe-9c58-274e585b666c.png)

**Comment by hanzei** [comment]
@dipak-demansol What version of `golangci-lint` are you using?

**Comment by hanzei** [comment]
@dipak-demansol Could you please test with `golangci-lint` `1.31.0`?

**Comment by dipak-demansol** [comment]
> @dipak-demansol What version of `golangci-lint` are you using?

go1.17.2

**Comment by hanzei** [comment]
My question was about `golangci-lint` not `go`.

**Comment by dipak-demansol** [comment]
> My question was about `golangci-lint` not `go`.

can you pls share me command with that i can find that version? because i search it but did't got any comamnd. 

> My question was about `golangci-lint` not `go`.

**Comment by dipak-demansol** [comment]
@hanzei in the plugin.json file thaere is a version = version": "1.2.0" is this a golangci-lint ver?

**Comment by dipak-demansol** [comment]
@hanzei this is the version golangci-lint has version 1.43.0 built from 861262b7 on 2021-11-03T11:57:46Z

**Comment by hanzei** [comment]
@dipak-demansol Could you please downgrade to `1.31.0` and test again?

**Comment by dipak-demansol** [comment]
> @dipak-demansol Could you please downgrade to `1.31.0` and test again?

yes, i installed the 1.31.0 version but it still detecting the 1.43.0 so i'm finding the way to remove the 1.43 and install 1.31.0

**Comment by dipak-demansol** [comment]
@hanzei Using The golangci-lint 1.31.0 its working.


![Screenshot from 2021-11-24 11-29-07](https://user-images.githubusercontent.com/89907719/143183352-554284e7-3aab-4ebb-8996-0b84c3e66c08.png)

**Comment by hanzei** [comment]
@dipak-demansol Glad we got that sorted out :+1:
