### ISSUE TITLE
Error submitting welcomebot form: "We could not decode the action"

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-welcomebot#97]
We're having an issue with Welcomebot, when a user selects an Action, Welcomebot returns the following error in the chat and nothing in the Mattermost logs:
`WelcomeBot Error: We could not decode the action`

We're on Mattermost Version: 7.7.1 and Welcombot: 1.2.0

Is anyone else seeing this issue?

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/856igob6yfgp8k68orftrsxm9a) *by `@hadleyso`*._

**Comment by hanzei** [comment]
As a first step, the error in https://github.com/mattermost/mattermost-plugin-welcomebot/blob/a4a10b47539aa1d72725a7ccee57d5799d4dcdfd/server/http_hooks.go#L14-L18 should be logged on the server side.

**Comment by Kshitij-Katiyar** [comment]
@mickmister @hanzei  Can you please give the steps to reproduce this error?  I have tried to set up the welcome bot with both automatic (users get added to channels automatically) and buttons (gets added by clicking the button) and both worked fine for me.

**Comment by hanzei** [comment]
@Kshitij-Katiyar I don't know how to reproduce the error. It's a community report. Logging the error is a good starting point.

**Comment by Kshitij-Katiyar** [comment]
> @Kshitij-Katiyar I don't know how to reproduce the error. It's a community report. Logging the error is a good starting point.

@hanzei Sure will create a PR for logging the error.
